version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test
    volumes:
      - pg:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env.test
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

volumes:
  pg: